const CONFIG={githubUser:'BokEumEom',pageSize:18};
const state={items:[],githubCount:0,siteSource:'all',siteQuery:'',siteSort:'recent',siteShown:CONFIG.pageSize,promptCategory:'all',promptQuery:''};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const sourceLabel={github:'GitHub',vercel:'Vercel',cloudflare:'Cloudflare',chatgpt:'ChatGPT Site',manual:'Archive'};
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=v=>{if(!v)return '—';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(d)};
function inferTags(repo){const text=`${repo.name} ${repo.description||''} ${repo.language||''}`.toLowerCase();const map=[['ai',['ai','llm','agent','rag','gemini']],['devops',['devops','terraform','kubernetes','aws','infra','sre']],['game',['game','quiz','puzzle','rpg','reversi','arcade']],['data',['data','trend','dashboard','scrape']],['web',['web','react','next','svelte','gatsby']],['ev',['ev','charging','electric']],['bible',['bible','catechism','proverbs']]];const tags=map.filter(([,keys])=>keys.some(k=>text.includes(k))).map(([t])=>t);if(repo.language)tags.push(repo.language.toLowerCase());return [...new Set(tags)].slice(0,6)}
function repoToItem(repo){return {id:`gh-${repo.id}`,type:'project',title:repo.name,summary:repo.description||'GitHub에 기록된 프로젝트',date:(repo.created_at||'').slice(0,10),updated:(repo.updated_at||'').slice(0,10),status:repo.archived?'archived':'repository',featured:false,sources:['github'],tags:inferTags(repo),githubRepo:repo.full_name,liveUrl:repo.homepage||'',preview:'',idea:'',prompt:'',notes:repo.language?`Primary language: ${repo.language}`:''}}
async function loadGithub(){const url=`https://api.github.com/users/${CONFIG.githubUser}/repos?per_page=100&sort=updated`;const r=await fetch(url,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`GitHub API ${r.status}`);const repos=(await r.json()).filter(r=>!r.fork);state.githubCount=repos.length;return repos.map(repoToItem)}
async function boot(){try{const [local,github]=await Promise.all([fetch('./data/archive.json').then(r=>{if(!r.ok)throw new Error('archive.json');return r.json()}),loadGithub().catch(e=>{console.warn(e);return []})]);const manual=local.items||[];const manualRepos=new Set(manual.map(i=>i.githubRepo).filter(Boolean).map(v=>v.toLowerCase()));state.items=[...manual,...github.filter(i=>!manualRepos.has((i.githubRepo||'').toLowerCase()))];$('#lastSynced').textContent=`Archive ${fmtDate(local.updated)} · GitHub ${state.githubCount} repos synced`;renderAll();openHashView()}catch(e){console.error(e);$('#lastSynced').textContent='아카이브 데이터를 불러오지 못했습니다.'}}
function allSites(){return state.items.filter(i=>i.type==='project')}
function allPrompts(){return state.items.filter(i=>i.type==='prompt')}
function allIdeas(){return state.items.filter(i=>i.type==='idea'||i.type==='experiment')}
function platform(item){const priority=['cloudflare','vercel','chatgpt','github'];return priority.find(s=>(item.sources||[]).includes(s))||(item.sources||[])[0]||'manual'}
function screenshot(item){if(item.preview)return item.preview;if(!item.liveUrl)return '';return `https://image.thum.io/get/width/1000/crop/625/noanimate/${item.liveUrl}`}
function bindImg(img,src,title){if(!src){img.style.display='none';return}img.src=src;img.alt=`${title} 미리보기`;img.addEventListener('error',()=>img.style.display='none',{once:true})}
function siteCard(item){const frag=$('#siteCardTemplate').content.cloneNode(true);const card=frag.querySelector('.site-card');const img=frag.querySelector('.site-preview img');bindImg(img,screenshot(item),item.title);frag.querySelector('.platform-badge').textContent=sourceLabel[platform(item)]||platform(item);frag.querySelector('time').textContent=fmtDate(item.updated||item.date);frag.querySelector('h3').textContent=item.title;frag.querySelector('.site-summary').textContent=item.summary||'설명이 없습니다.';const tags=frag.querySelector('.tag-list');(item.tags||[]).slice(0,5).forEach(t=>{const s=document.createElement('span');s.className='tag';s.textContent=`#${t}`;tags.appendChild(s)});const links=frag.querySelector('.site-card-links');if(item.liveUrl)links.insertAdjacentHTML('beforeend',`<a href="${esc(item.liveUrl)}" target="_blank" rel="noreferrer" data-stop>Live ↗</a>`);if(item.githubRepo)links.insertAdjacentHTML('beforeend',`<a href="https://github.com/${esc(item.githubRepo)}" target="_blank" rel="noreferrer" data-stop>Code ↗</a>`);links.querySelectorAll('[data-stop]').forEach(a=>a.addEventListener('click',e=>e.stopPropagation()));card.addEventListener('click',()=>openDetail(item));card.addEventListener('keydown',e=>{if(e.key==='Enter'){openDetail(item)}});return frag}
function promptCard(item){const frag=$('#promptCardTemplate').content.cloneNode(true);const card=frag.querySelector('.prompt-card');const img=frag.querySelector('.prompt-preview img');bindImg(img,item.preview||'',item.title);if(item.preview)frag.querySelector('.prompt-fallback').style.display='none';frag.querySelector('.prompt-fallback strong').textContent=item.category?item.category.toUpperCase():'PROMPT';frag.querySelector('.model-badge').textContent=item.model||'ChatGPT';frag.querySelector('.prompt-kind').textContent=item.category||'prompt';frag.querySelector('h3').textContent=item.title;const copy=frag.querySelector('.copy-mini');copy.addEventListener('click',async e=>{e.stopPropagation();await copyPrompt(item.prompt,copy)});card.addEventListener('click',()=>openDetail(item));card.addEventListener('keydown',e=>{if(e.key==='Enter')openDetail(item)});return frag}
async function copyPrompt(text,button){if(!text)return;try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Copied!';setTimeout(()=>button.textContent=old,1200)}catch{button.textContent='Copy failed'}}
function renderStats(){$('#siteCount').textContent=allSites().length;$('#promptCount').textContent=allPrompts().length;$('#ideaCount').textContent=allIdeas().length;$('#githubCount').textContent=state.githubCount}
function renderHome(){const sites=$('#homeSites');sites.innerHTML='';let picks=allSites().filter(i=>i.featured).slice(0,6);if(picks.length<3)picks=[...picks,...allSites().filter(i=>!picks.includes(i)).slice(0,3-picks.length)];picks.forEach(i=>sites.appendChild(siteCard(i)));const prompts=$('#homePrompts');prompts.innerHTML='';allPrompts().filter(i=>i.featured||i.preview).slice(0,8).forEach(i=>prompts.appendChild(promptCard(i)))}
function filteredSites(){const q=state.siteQuery.trim().toLowerCase();let items=allSites().filter(i=>state.siteSource==='all'||(i.sources||[]).includes(state.siteSource)).filter(i=>!q||[i.title,i.summary,i.idea,...(i.tags||[])].join(' ').toLowerCase().includes(q));items.sort((a,b)=>state.siteSort==='name'?a.title.localeCompare(b.title):state.siteSort==='oldest'?(a.updated||a.date||'').localeCompare(b.updated||b.date||''):(b.updated||b.date||'').localeCompare(a.updated||a.date||''));return items}
function renderSites(){const items=filteredSites(),grid=$('#siteGrid');grid.innerHTML='';items.slice(0,state.siteShown).forEach(i=>grid.appendChild(siteCard(i)));if(!items.length)grid.innerHTML='<div class="empty">조건에 맞는 사이트가 없습니다.</div>';$('#siteResultCount').textContent=`${items.length}개 사이트/프로젝트`;$('#siteMore').style.display=state.siteShown>=items.length?'none':'block'}
function filteredPrompts(){const q=state.promptQuery.trim().toLowerCase();return allPrompts().filter(i=>state.promptCategory==='all'||i.category===state.promptCategory).filter(i=>!q||[i.title,i.summary,i.prompt,i.model,i.category,...(i.tags||[])].join(' ').toLowerCase().includes(q)).sort((a,b)=>(b.updated||b.date||'').localeCompare(a.updated||a.date||''))}
function renderPrompts(){const items=filteredPrompts(),grid=$('#promptGrid');grid.innerHTML='';items.forEach(i=>grid.appendChild(promptCard(i)));if(!items.length)grid.innerHTML='<div class="empty">조건에 맞는 프롬프트가 없습니다.</div>';$('#promptResultCount').textContent=`${items.length}개 프롬프트`}
function renderIdeas(){const grid=$('#ideaGrid');grid.innerHTML='';allIdeas().sort((a,b)=>(b.updated||b.date||'').localeCompare(a.updated||a.date||'')).forEach(i=>{const el=document.createElement('article');el.className='idea-card';el.innerHTML=`<small>${esc(i.type.toUpperCase())} · ${esc(fmtDate(i.updated||i.date))}</small><h3>${esc(i.title)}</h3><p>${esc(i.summary||i.idea||'')}</p><div class="tag-list">${(i.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div>`;el.addEventListener('click',()=>openDetail(i));grid.appendChild(el)})}
function renderAll(){renderStats();renderHome();renderSites();renderPrompts();renderIdeas()}
function openDetail(item){const media=item.type==='project'?screenshot(item):item.preview;const links=[];if(item.liveUrl)links.push(`<a href="${esc(item.liveUrl)}" target="_blank" rel="noreferrer">Live site ↗</a>`);if(item.githubRepo)links.push(`<a href="https://github.com/${esc(item.githubRepo)}" target="_blank" rel="noreferrer">GitHub ↗</a>`);if(item.type==='prompt'&&item.prompt)links.push('<button id="copyPromptFull" class="copy-prompt" type="button">Copy prompt</button>');let html=`<div class="dialog-inner"><p class="eyebrow">${esc(item.type.toUpperCase())}${item.model?` · ${esc(item.model)}`:''}</p><h2>${esc(item.title)}</h2><p class="dialog-summary">${esc(item.summary||'')}</p>`;if(media)html+=`<div class="dialog-media"><img src="${esc(media)}" alt="${esc(item.title)} preview"></div>`;html+=`<div class="tag-list">${(item.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div><div class="dialog-links">${links.join('')}</div>`;[['Idea',item.idea],['Prompt',item.prompt],['Notes',item.notes]].forEach(([title,value])=>{if(value)html+=`<section class="detail-block"><h3>${title}</h3>${title==='Prompt'?`<pre>${esc(value)}</pre>`:`<p>${esc(value)}</p>`}</section>`});html+=`<section class="detail-block"><h3>Archive metadata</h3><p>${esc(fmtDate(item.date))} → ${esc(fmtDate(item.updated||item.date))} · ${esc(item.status||'')}</p></section></div>`;$('#dialogContent').innerHTML=html;$('#detailDialog').showModal();$('#copyPromptFull')?.addEventListener('click',e=>copyPrompt(item.prompt,e.currentTarget))}
function setView(view){const valid=['home','sites','prompts','ideas'];if(!valid.includes(view))view='home';$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===`view-${view}`));$$('[data-view-link]').forEach(b=>b.classList.toggle('active',b.dataset.viewLink===view&&b.classList.contains('nav-link')));history.replaceState(null,'',`#${view}`);scrollTo({top:0,behavior:'instant'})}
function openHashView(){setView(location.hash.replace('#','')||'home')}
function bind(){$$('[data-view-link]').forEach(el=>el.addEventListener('click',e=>{if(el.tagName==='A')e.preventDefault();setView(el.dataset.viewLink)}));$('#siteSearch').addEventListener('input',e=>{state.siteQuery=e.target.value;state.siteShown=CONFIG.pageSize;renderSites()});$('#siteSort').addEventListener('change',e=>{state.siteSort=e.target.value;renderSites()});$$('[data-site-source]').forEach(b=>b.addEventListener('click',()=>{$$('[data-site-source]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.siteSource=b.dataset.siteSource;state.siteShown=CONFIG.pageSize;renderSites()}));$('#siteMore').addEventListener('click',()=>{state.siteShown+=CONFIG.pageSize;renderSites()});$('#promptSearch').addEventListener('input',e=>{state.promptQuery=e.target.value;renderPrompts()});$$('[data-prompt-category]').forEach(b=>b.addEventListener('click',()=>{$$('[data-prompt-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.promptCategory=b.dataset.promptCategory;renderPrompts()}));$('#dialogClose').addEventListener('click',()=>$('#detailDialog').close());$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});$('#themeToggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('archive-theme',next)});const saved=localStorage.getItem('archive-theme');if(saved)document.documentElement.dataset.theme=saved;else if(matchMedia('(prefers-color-scheme: light)').matches)document.documentElement.dataset.theme='light';$('#year').textContent=new Date().getFullYear();window.addEventListener('hashchange',openHashView)}
bind();boot();