const CONFIG={githubUser:'BokEumEom',pageSize:18};
const state={items:[],filtered:[],type:'all',source:'all',query:'',sort:'recent',shown:CONFIG.pageSize};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const typeLabel={project:'Project',prompt:'Prompt',idea:'Idea',experiment:'Experiment'};
const sourceLabel={github:'GitHub',vercel:'Vercel',cloudflare:'Cloudflare',chatgpt:'ChatGPT Site',manual:'Notes'};
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function fmtDate(v){if(!v)return '날짜 없음';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(d)}
function inferTags(repo){const text=`${repo.name} ${repo.description||''} ${repo.language||''}`.toLowerCase();const map=[['ai',['ai','llm','agent','rag','gemini']],['devops',['devops','terraform','kubernetes','aws','infra','sre']],['game',['game','quiz','puzzle','rpg','reversi','arcade']],['data',['data','trend','dashboard','scrape']],['web',['web','react','next','svelte','gatsby']],['ev',['ev','charging','electric']],['bible',['bible','catechism','proverbs']]];const tags=map.filter(([,keys])=>keys.some(k=>text.includes(k))).map(([t])=>t);if(repo.language)tags.push(repo.language.toLowerCase());return [...new Set(tags)].slice(0,5)}
function repoToItem(repo){return {id:`gh-${repo.id}`,type:'project',title:repo.name,summary:repo.description||'GitHub에 기록된 프로젝트',date:(repo.created_at||'').slice(0,10),updated:(repo.updated_at||'').slice(0,10),status:repo.archived?'archived':'repository',featured:false,sources:['github'],tags:inferTags(repo),githubRepo:repo.full_name,liveUrl:repo.homepage||'',idea:'',prompt:'',notes:repo.language?`Primary language: ${repo.language}`:''}}
async function loadGithub(){const url=`https://api.github.com/users/${CONFIG.githubUser}/repos?per_page=100&sort=updated`;const r=await fetch(url,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`GitHub API ${r.status}`);return (await r.json()).filter(r=>!r.fork).map(repoToItem)}
async function boot(){try{const [local,github]=await Promise.all([fetch('./data/archive.json').then(r=>{if(!r.ok)throw new Error('archive.json');return r.json()}),loadGithub().catch(e=>({error:e,items:[]}))]);const gh=Array.isArray(github)?github:github.items||[];const manual=local.items||[];const manualRepos=new Set(manual.map(i=>i.githubRepo).filter(Boolean).map(v=>v.toLowerCase()));state.items=[...manual,...gh.filter(i=>!manualRepos.has((i.githubRepo||'').toLowerCase()))];$('#lastSynced').textContent=`${fmtDate(local.updated)} · GitHub ${gh.length} repos synced`;if(github.error)$('#lastSynced').title='GitHub API를 불러오지 못해 로컬 데이터만 표시합니다.';renderAll()}catch(e){console.error(e);$('#lastSynced').textContent='아카이브를 불러오지 못했습니다.';$('#archiveGrid').innerHTML='<div class="error-note">data/archive.json을 확인해주세요.</div>'}}
function parseQuery(q){const tokens={plain:[],type:null,source:null,tag:null};q.trim().split(/\s+/).filter(Boolean).forEach(part=>{const [k,...rest]=part.split(':');const val=rest.join(':').toLowerCase();if(val&&['type','source','tag'].includes(k.toLowerCase()))tokens[k.toLowerCase()]=val;else tokens.plain.push(part.toLowerCase())});return tokens}
function applyFilters(){const q=parseQuery(state.query);let arr=state.items.filter(item=>{if(state.type!=='all'&&item.type!==state.type)return false;if(state.source!=='all'&&!(item.sources||[]).includes(state.source))return false;if(q.type&&item.type!==q.type)return false;if(q.source&&!(item.sources||[]).includes(q.source))return false;if(q.tag&&!(item.tags||[]).map(t=>t.toLowerCase()).includes(q.tag))return false;const hay=[item.title,item.summary,item.idea,item.prompt,item.notes,...(item.tags||[]),...(item.sources||[])].join(' ').toLowerCase();return q.plain.every(p=>hay.includes(p))});arr.sort((a,b)=>state.sort==='name'?a.title.localeCompare(b.title):state.sort==='oldest'?(a.updated||a.date||'').localeCompare(b.updated||b.date||''):(b.updated||b.date||'').localeCompare(a.updated||a.date||''));state.filtered=arr}
function makeCard(item,featured=false){const t=$('#cardTemplate').content.cloneNode(true);const card=t.querySelector('.archive-card');card.dataset.id=item.id;t.querySelector('.type-badge').textContent=typeLabel[item.type]||item.type;t.querySelector('.source-badge').textContent=(item.sources||[]).map(s=>sourceLabel[s]||s).join(' · ');t.querySelector('h4').textContent=item.title;t.querySelector('.card-summary').textContent=item.summary||'설명이 없습니다.';const tags=t.querySelector('.tag-list');(item.tags||[]).slice(0,5).forEach(tag=>{const el=document.createElement('span');el.className='tag';el.textContent=`#${tag}`;tags.appendChild(el)});t.querySelector('time').textContent=fmtDate(item.updated||item.date);t.querySelector('.status').textContent=item.status||'';if(featured)t.querySelector('.card-art').style.height='168px';card.addEventListener('click',()=>openItem(item));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openItem(item)}});return t}
function renderStats(){const c=t=>state.items.filter(i=>i.type===t).length;$('#projectCount').textContent=c('project');$('#promptCount').textContent=c('prompt');$('#ideaCount').textContent=c('idea');$('#experimentCount').textContent=c('experiment')}
function renderFeatured(){const wrap=$('#featuredWrap'),grid=$('#featuredGrid');grid.innerHTML='';const items=state.filtered.filter(i=>i.featured).slice(0,6);wrap.hidden=!items.length;items.forEach(i=>grid.appendChild(makeCard(i,true))}
function renderGrid(){const grid=$('#archiveGrid');grid.innerHTML='';const items=state.filtered.slice(0,state.shown);items.forEach(i=>grid.appendChild(makeCard(i)));$('#resultSummary').textContent=`${state.filtered.length}개 항목 · 전체 ${state.items.length}개`;$('#emptyState').hidden=state.filtered.length!==0;$('#loadMore').hidden=state.shown>=state.filtered.length}
function renderTimeline(){const list=$('#timelineList');list.innerHTML='';[...state.items].sort((a,b)=>(b.updated||b.date||'').localeCompare(a.updated||a.date||'')).slice(0,12).forEach(item=>{const row=document.createElement('div');row.className='timeline-item';row.innerHTML=`<span class="timeline-date">${esc(fmtDate(item.updated||item.date))}</span><button type="button" class="timeline-title" style="all:unset;cursor:pointer">${esc(item.title)}</button><span class="timeline-meta">${esc(typeLabel[item.type]||item.type)} · ${esc((item.sources||[])[0]||'manual')}</span>`;row.querySelector('button').addEventListener('click',()=>openItem(item));list.appendChild(row)})}
function renderAll(){applyFilters();renderStats();renderFeatured();renderGrid();renderTimeline()}
function openItem(item){const links=[];if(item.liveUrl)links.push(`<a href="${esc(item.liveUrl)}" target="_blank" rel="noreferrer">Live site ↗</a>`);if(item.githubRepo)links.push(`<a href="https://github.com/${esc(item.githubRepo)}" target="_blank" rel="noreferrer">GitHub ↗</a>`);const sources=(item.sources||[]).map(s=>sourceLabel[s]||s).join(' · ');let html=`<div class="dialog-inner"><p class="eyebrow">${esc(typeLabel[item.type]||item.type)} · ${esc(sources)}</p><h2>${esc(item.title)}</h2><p class="dialog-summary">${esc(item.summary||'')}</p><div class="tag-list">${(item.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div><div class="dialog-links">${links.join('')}</div>`;[['Idea',item.idea],['Prompt',item.prompt],['Notes',item.notes]].forEach(([title,value])=>{if(value)html+=`<section class="detail-block"><h3>${title}</h3>${title==='Prompt'?`<pre>${esc(value)}</pre>`:`<p>${esc(value)}</p>`}</section>`});html+=`<section class="detail-block"><h3>Archive metadata</h3><p>${esc(fmtDate(item.date))} → ${esc(fmtDate(item.updated||item.date))} · ${esc(item.status||'')}</p></section></div>`;$('#dialogContent').innerHTML=html;$('#itemDialog').showModal()}
function bind(){$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;state.shown=CONFIG.pageSize;renderAll()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderAll()});$('#loadMore').addEventListener('click',()=>{state.shown+=CONFIG.pageSize;renderGrid()});$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.filter;state.shown=CONFIG.pageSize;renderAll()}));$$('[data-source]').forEach(b=>b.addEventListener('click',()=>{$$('[data-source]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.source=b.dataset.source;state.shown=CONFIG.pageSize;renderAll()}));$$('[data-jump-filter]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.jumpFilter;document.querySelector(`[data-filter="${key}"]`)?.click();location.hash='archive'}));document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape'&&$('#itemDialog').open)$('#itemDialog').close()});$('#dialogClose').addEventListener('click',()=>$('#itemDialog').close());$('#itemDialog').addEventListener('click',e=>{if(e.target===$('#itemDialog'))$('#itemDialog').close()});$('#themeToggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('archive-theme',next)});$('#year').textContent=new Date().getFullYear();const saved=localStorage.getItem('archive-theme');if(saved)document.documentElement.dataset.theme=saved;else if(matchMedia('(prefers-color-scheme: light)').matches)document.documentElement.dataset.theme='light'}
bind();boot();
